import {createServer} from 'node:http';
import {readFileSync,writeFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require('playwright');
const root=new URL('../',import.meta.url),server=createServer((req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;const file=new URL('.'+(path==='/'?'/examples/standalone.html':path),root);if(!file.href.startsWith(root.href))throw Error();res.setHeader('content-type',path.endsWith('.js')?'text/javascript':path.endsWith('.png')?'image/png':'text/html');res.end(readFileSync(file));}catch{res.statusCode=404;res.end();}});
await new Promise(resolve=>server.listen(4898,'127.0.0.1',resolve));
const browser=await chromium.launch({...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH ? {executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH} : {}),headless:true,args:['--no-sandbox']});const results=[];
try{for(const width of [1280,375]){
 const page=await browser.newPage({viewport:{width,height:1000}}),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto('http://127.0.0.1:4898');await page.waitForFunction(()=>window.ready);
 const sq=name=>page.locator(`#board .sq[data-square="${name}"]`);
 assert.equal(await page.locator('#board .sq').count(),64);assert.equal(await page.locator('#secondary .sq').count(),64);
 assert.equal(await page.locator('#board .badge').getAttribute('aria-label'),'Host-defined recommended piece');assert.equal(await page.locator('#board svg.arrows').getAttribute('aria-label'),'Host-defined advance');
 const rect=await page.locator('#board .board').boundingBox();assert.ok(Math.abs(rect.width-rect.height)<1);assert.ok(rect.width<=width);
 await sq('e2').click();await sq('e4').click();assert.equal(await page.evaluate(()=>window.intents.at(-1).uci),'e2e4');assert.equal(await page.evaluate(()=>window.demoState.position.e4),'P');assert.equal(await page.locator('#secondary .sq[data-square="e2"] img').count(),1);
 await page.locator('#reset').click();const source=await sq('b1').boundingBox(),target=await sq('c3').boundingBox();await page.mouse.move(source.x+source.width/2,source.y+source.height/2);await page.mouse.down();await page.mouse.move(target.x+target.width/2,target.y+target.height/2,{steps:10});await page.mouse.up();assert.equal(await page.evaluate(()=>window.intents.at(-1).uci),'b1c3');assert.equal(await page.evaluate(()=>window.intents.at(-1).source),'drag');
 await page.locator('#reset').click();await sq('e2').focus();await page.keyboard.press('Enter');await page.keyboard.press('ArrowUp');await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>window.intents.at(-1).uci),'e2e3');assert.equal(await page.evaluate(()=>window.intents.at(-1).source),'keyboard');
 await page.locator('#promotion').click();await sq('a7').click();await sq('a8').click();assert.equal(await page.locator('#board [role="dialog"]').count(),1);assert.equal(await page.locator('#board .promotion-choice').count(),4);await page.keyboard.press('Escape');assert.equal(await page.locator('#board [role="dialog"]').count(),0);assert.equal(await page.evaluate(()=>window.demoState.position.a7),'P');
 await sq('a8').click();await page.getByRole('button',{name:'Promote to knight'}).click();assert.equal(await page.evaluate(()=>window.intents.at(-1).uci),'a7a8n');assert.equal(await page.evaluate(()=>window.demoState.position.a8),'N');
 await page.locator('#promotion').click();await page.locator('#flip').click();assert.equal(await page.locator('#board .sq').first().getAttribute('data-square'),'h1');await sq('a7').click();await sq('a8').click();await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.querySelector('#board').firstElementChild.shadowRoot.activeElement.getAttribute('aria-label')),'Promote to rook');await page.locator('#lock').click();assert.equal(await page.locator('#board [role="dialog"]').count(),0);
 const count=await page.evaluate(()=>window.intents.length);await sq('a7').click();await sq('a8').click();assert.equal(await page.evaluate(()=>window.intents.length),count);
 await page.locator('#reset').click();await sq('e2').focus();await page.evaluate(()=>window.boardDemo.set({...window.demoState,arrows:[{from:'e2',to:'e3',label:'<script>host text</script>',color:'red'}]}));assert.equal(await page.evaluate(()=>document.querySelector('#board').firstElementChild.shadowRoot.activeElement.dataset.square),'e2');assert.equal(await page.locator('#board svg.arrows').getAttribute('aria-label'),'<script>host text</script>');
 await page.locator('#dispose').click();assert.equal(await page.locator('#board').innerHTML(),'');assert.equal(await page.locator('#secondary .sq').count(),64);await page.evaluate(()=>{let threw=false;try{window.boardDemo.board.update(window.demoState);}catch{threw=true;}if(!threw)throw Error('Update after disposal accepted');});assert.deepEqual(errors,[]);
 results.push({width,squares:64,click:true,drag:true,keyboard:true,promotionCancel:true,underpromotion:'a7a8n',flippedPromotion:true,focusTrap:true,permissionRevocation:true,arbitraryOverlay:true,focusRetention:true,multiInstance:true,disposal:true,errors});await page.close();
}}finally{await browser.close();server.close();}
const manifest=JSON.parse(readFileSync(new URL('package.json',root),'utf8'));
writeFileSync(new URL('./browser-results.json',root),JSON.stringify({node:process.version,engine:'Chromium '+(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||'Playwright bundled browser'),installedPackage:`${manifest.name}@${manifest.version}`,results},null,2));console.log(JSON.stringify(results));
